#!/bin/sh

. "$(dirname "$0")/.common.sh"
trap_fail

: ${src_name=volatility}
: ${ver:=2.6}
: ${src:=https://github.com/volatilityfoundation/${src_name}.git}
: ${src_dir:=$(git_branch=$ver dl_file $src)}
: ${pip_pkgs:=distorm3 yara ujson openpyxl}

pip_inst ${pip_pkgs}
pip_inst "$src_dir"

exit_succ
