#!/bin/sh

. "$(dirname "$0")/.common.sh"
trap_fail

: ${src_name=volatility}
: ${ver:=2.6}
: ${src:=https://github.com/volatilityfoundation/${src_name}.git}
: ${src_dir:=$(git_branch=$ver dl_file $src)}
: ${pip_pkgs:=distorm3 yara ujson openpyxl}

apt-get install -y python-dev python-pip

CPPFLAGS="-I/opt/include" LDFLAGS="-Wl,-rpath=/opt/lib -L/opt/lib" pip install \
    --download-cache "$dl_cache_dir/pip/dl" --upgrade \
    --install-option="--prefix=/opt" --root "$DESTDIR" \
    ${pip_switches} ${pip_pkgs}

dl_compile_and_install "$src_dir" /opt $DESTDIR

exit_succ
