#!/bin/sh

. "$(dirname "$0")/.common.sh"
trap_fail

: ${pytsk_url:=https://github.com/py4n6/pytsk.git}

: ${pytsk_src:=$(dl_file "$pytsk_url")}

(cd "$pytsk_src/sleuthkit" && autoreconf -i )
dl_compile_and_install "$pytsk_src" /opt "$DESTDIR" ""

exit_succ
