#!/bin/sh

. "$(dirname "$0")/.common.sh"
trap_fail

as_root apt-get -y install python-dev libyaml-dev python-pip

: ${plaso_ver:=$(curl -s https://api.github.com/repos/log2timeline/plaso/releases | jq -r .[0].tag_name)}
: ${plaso_src:=$(git_branch=$plaso_ver dl_file https://github.com/log2timeline/plaso.git)}

(
  cd "$plaso_src"
  apt-get --allow-unauthenticated -y install $(awk '/^lib.*-python/{print $1}' requirements.txt)
  CPPFLAGS="-I/opt/include" LDFLAGS="-Wl,-rpath=/opt/lib -L/opt/lib" pip \
    install --download-cache "$dl_cache_dir/pip" -r requirements.txt \
    --install-option="--prefix=/opt" --root "$DESTDIR"
)

dl_compile_and_install "$plaso_src" /opt "$DESTDIR"

exit_succ
