#!/bin/sh

. "$(dirname "$0")/.common.sh"

trap_fail

as_root apt-get -y install python-dev libfuse-dev uuid-dev libbz2-dev libewf-dev libtalloc-dev

: ${ant_url:=http://ftp.kddilabs.jp/infosystems/apache//ant/binaries/apache-ant-1.9.4-bin.tar.bz2}
: ${tsk_url:=https://github.com/sleuthkit/sleuthkit/releases/download/sleuthkit-4.3.0/sleuthkit-4.3.0.tar.gz}

if which javac >/dev/null;then
  which ant >/dev/null || {
    test -d ant-bin/bin || {
      mkdir -p ant-bin
      curl "$ant_url" | tar xj -C ant-bin --strip-components=1
    }
    export PATH="$PATH:$PWD/ant-bin/bin"
  }
fi

dl_compile_and_install "$tsk_url" /opt "$DESTDIR" "" --with-afflib="$DESTDIR/opt"

exit_succ
