#!/bin/sh

. "$(dirname "$0")/.common.sh"
set -e

mkdir -p "$DESTDIR/opt/bin"
wget -O "$DESTDIR/opt/bin/amcache.py" https://raw.githubusercontent.com/williballenthin/python-registry/master/samples/amcache.py
chmod +x "$DESTDIR/opt/bin/amcache.py"
