#!/bin/sh

. /opt/LiveBootUtils/scripts/common.func
set -e

: ${src_name=hindsight}
: ${src:=https://github.com/obsidianforensics/${src_name}.git}
: ${src_dir:=$HOME/.cache/lbu-compile/$(echo -n "$src" | md5sum | cut -c1-8)-${src_name}-src}

test -d "$src_dir" && (cd "$src_dir" ; git pull) || git clone --depth=1 "$src" "$src_dir"
(cd "$src_dir" ; git archive --format=tar --prefix=opt/hindsight/ HEAD hindsight.py documentation plugins) | tar xv -C "$DESTDIR"
