#!/bin/sh

. "$(dirname "$0")/.common.sh"
: ${prefix:=/opt}

set -e -x

pip_inst rekall

for pkg in rekall_gui/plugins/webconsole manuskript;do
  lib_d="$DESTDIR$prefix/lib/python2.7/site-packages/$pkg"
  inst_d="$DESTDIR$prefix/$pkg"
  test -d "$lib_d" -a -d "$inst_d/static" || continue
  test -L "$lib_d/static" -o -d "$lib_d/static" || {
    mv "$inst_d/static" "$lib_d"
    (rm_d="$inst_d"; while test -n "$rm_d" && rmdir "$rm_d"; do rm_d=${rm_d%/*};done)
  }
done
