#!/bin/sh

. "$(dirname "$0")/.common.sh"
set -e

mkdir -p "$DESTDIR/opt/bin"
wget -O "$DESTDIR/opt/bin/rfcparse.py" https://raw.githubusercontent.com/sysforensics/RecentFileCacheParser/master/rfcparse.py
