#!/bin/sh

. /opt/LiveBootUtils/scripts/common.func
set -e

: ${dl_url:=https://raw.githubusercontent.com/mdegrazia/SQLite-Deleted-Records-Parser/master/sqlparse_v1.3.py}
: ${fname:=sqlparse.py}
: ${bin_name:=sqlparse}

mkdir -p "$DESTDIR/opt/bin"
mv "$(dl_file "$dl_url")" "$DESTDIR/opt/bin/$fname"
test -L "$DESTDIR/opt/bin/$bin_name" || ln -s _wrap-py "$DESTDIR/opt/bin/$bin_name" 
